apiVersion: 1

datasources:
  - name: recognize_influxdb_datasource
    type: influxdb
    access: proxy
    database: recognize
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
  - name: detect_influxdb_datasource
    type: influxdb
    access: proxy
    database: detect
    orgId: 1
    url: http://influxdb:8086
    isDefault: false
  - name: verify_influxdb_datasource
    type: influxdb
    access: proxy
    database: verify
    orgId: 1
    url: http://influxdb:8086
    isDefault: false
  - name: face_verify_influxdb_datasource
    type: influxdb
    access: proxy
    database: face_verify
    orgId: 1
    url: http://influxdb:8086
    isDefault: false
