#################################################################################################
# Docker compose override file for deploy allication stack to the CompreFace project environments
#
# Usage: HOSTNAME=$HOSTNAME sudo docker-compose -f docker-compose.yml -f docker-compose.env.yml up -d
#
# Note: a) We need to provide $HOSTNAME to mount TLS certs correctly for each environment.
#       b) We also mount nginx configuration with HTTPS instead of the default one.
#
#################################################################################################
version: '3.4'

volumes:
  postgres-data:

services:
  compreface-fe:
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/archive/$HOSTNAME/fullchain1.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/archive/$HOSTNAME/privkey1.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "8000:80"
      - "443:443"
