#################################################################################################
# Docker compose override file for deploy allication stack to the CompreFace project environments
#
# Usage: HOSTNAME=$HOSTNAME sudo docker-compose -f docker-compose.yml -f docker-compose.env.yml up -d
#
# Note: a) We need to provide $HOSTNAME to mount TLS certs correctly for each environment.
#       b) We also mount nginx configuration with HTTPS instead of the default one.
#
#################################################################################################
version: '3.4'

volumes:
  postgres-data:

services:
  compreface-fe:
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NGINX_HOST=$HOSTNAME
    ports:
      - "8000:80"
      - "443:443"
