POST http://localhost:8081/recognize
Content-Type: multipart/form-data; boundary=file
x-frs-api-key: 3dcd29bc-7f53-4039-a2c2-5554e4517d57

--file
Content-Disposition: form-data; name="file"; filename="face.jpg"

#< /path-to-file-face.jpg

--file
Content-Disposition: form-data; name="limit"

1
###