name: (Release) Build and Push Default CompreFace version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PWD }}

    # Set up buildx for multi platform images build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and Push images
      env:
        VERSION: ${{ github.event.inputs.version }}
        APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
      working-directory: ./dev/
      # The option --push was added in version 2.16.0, so we are additionally updating docker compose
      # https://docs.docker.com/compose/release-notes/#2160
      run: |
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 \
          -o /usr/local/bin/docker-compose
        sed -i 's/registry=/registry=exadel\//g' .env
        docker-compose -f docker-compose.yml -f docker-compose.multiplatform.yml build \
          --push \
          --build-arg APPERY_API_KEY=${APPERY_API_KEY}
        sed -i 's/latest/${VERSION}/g' .env
        docker-compose -f docker-compose.yml -f docker-compose.multiplatform.yml build \
          --push \
          --build-arg APPERY_API_KEY=${APPERY_API_KEY}

