name: (Release) Build and Push Default CompreFace version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build images
        env:
          VERSION: ${{ github.event.inputs.version }}
          APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
        working-directory: ./dev/
        run: |
          sed -i 's/registry=/registry=exadel\//g' .env
          docker-compose build --build-arg APPERY_API_KEY=${APPERY_API_KEY}
          sed -i 's/latest/${VERSION}/g' .env
          docker-compose build --build-arg APPERY_API_KEY=${APPERY_API_KEY}
          docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Push images to Docker Hub
        working-directory: ./dev/
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker-compose push
          sed -i 's/${VERSION}/latest/g' .env
          docker-compose push